# Generated by Django 6.0.5 on 2026-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_interviewnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewnote',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='notes/covers/'),
        ),
    ]
