# Generated by Django 6.0.5 on 2026-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewnote',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='cover_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
