# Generated by Django 6.0.5 on 2026-06-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_inlineannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlineannotation',
            name='annotation_type',
            field=models.CharField(default='text', max_length=10),
        ),
    ]
